// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGarage.Data;

#nullable disable

namespace TheGarage.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheGarage.Data.Entities.Car", b =>
                {
                    b.Property<string>("RegistryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearModel")
                        .HasColumnType("int");

                    b.HasKey("RegistryNumber");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            RegistryNumber = "OMH525",
                            Brand = "Volksvagen",
                            Color = "White",
                            Model = "Golf Manhattan",
                            YearModel = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
